env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,xcb
env = GDK_SCALE,1
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland
env = GTK_THEME,Adwaita:dark
env = ICON_THEME,Reversal
env = GTK_ICON_THEME,Reversal
env = MOZ_ENABLE_WAYLAND,1
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Reversal
env = HYPRCURSOR_SIZE,2
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = XAUTHORITY,$HOME/.Xauthority

exec = gsettings set org.gnome.desktop.interface cursor-size 24

xwayland {
  enabled = true
  force_zero_scaling = true
}

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XAUTHORITY DISPLAY
