window_size = 600 300
border_size = 2
border_radius = 16

background = rgba(1e1e2eee)
border_color = rgba(cba6f7ff)
text_color = rgba(cdd6f4ff)
placeholder_color = rgba(6c7086ff)

opacity = 0.95
max_items = 8
prompt = "󰍉  Search"
show_icons = true

fuzzy = true
close_on_launch = true

font_family = "JetBrainsMono Nerd Font"
font_size = 14
